[package]
name = "wasm"
version = "0.1.0"
edition = "2024"

[dependencies]
js-sys = "0.3.85"
peuler = { path = "../../../peuler" }
pmath = { path = "../../../pmath" }
wasm-bindgen = "0.2.108"

[lib]
name = "wasm"
crate-type = ["cdylib"]
path = "src/lib.rs"
